python src/evaluate.py \
    --seed=0 \
    --data_dir="data" \
    --model_type="gpt2" \
    --bos_token="<bos>" \
    --sp1_token="<sp1>" \
    --sp2_token="<sp2>" \
    --gpu="0" \
    --max_len=1024 \
    --top_p=0.8 \
    --ckpt_dir="saved_models" \
    --ckpt_name="saved_models\gpt2\BERT_best_ckpt_epoch=19_valid_loss=1.7586.ckpt"\