python src/main_cp.py \
    --seed=0 \
    --mode="train" \
    --data_dir="data" \
    --train_prefix="train" \
    --valid_prefix="valid" \
    --model_type="gpt2" \
    --bos_token="<bos>" \
    --sp1_token="<sp1>" \
    --sp2_token="<sp2>" \
    --gpu="0" \
    --lr=1e-5 \
    --warmup_ratio=0.0 \
    --batch_size=6 \
    --num_workers=0 \
    --num_epochs=5 \
    --max_len=1024 \
    --max_turns=5 \
    --ckpt_dir="saved_models" \
    --ckpt_name="saved_models\gpt2\best_ckpt_epoch=19_valid_loss=2.3336_question_loss.ckpt"\
    --exp_name="new_LDA_topic_loss" \
    --w_question_loss=0.25 \
    --w_topic_loss=0.25 \